### ISSUE TITLE
Help~

### ISSUE THREAD

**Issue by Peppa-cs** [chiehpower/Setup-deeplearning-tools#1]
Hello, I am a graduate student on the mainland. I now use jetson for image classification. Since I can't access the external network on the mainland, after trying many methods, I still can't build onnxruntime. Because when building onnxruntime, you need to git clone the resources on Google. , I tried to use Trojan and other wall-over software on Jetson, but they do not support on ARM architecture. Therefore, I would take the liberty to ask if I can add your contact information and send me your whl file.

**Comment by chiehpower** [comment]
> Hello, I am a graduate student on the mainland. I now use jetson for image classification. Since I can't access the external network on the mainland, after trying many methods, I still can't build onnxruntime. Because when building onnxruntime, you need to git clone the resources on Google. , I tried to use Trojan and other wall-over software on Jetson, but they do not support on ARM architecture. Therefore, I would take the liberty to ask if I can add your contact information and send me your whl file.

Hi @Peppa-cs ,

Maybe you can try to find on [Gitee](https://gitee.com/). There are also many repositories which are clone from GitHub.
I am sorry that I don't really understand what Chinese network problem is, so probably you can ask your classmates or other Chinese how to fix this problem because I believe you won't only need to build `onnxruntime` from source.

Thanks.

**Comment by Peppa-cs** [comment]
> > Hello, I am a graduate student on the mainland. I now use jetson for image classification. Since I can't access the external network on the mainland, after trying many methods, I still can't build onnxruntime. Because when building onnxruntime, you need to git clone the resources on Google. , I tried to use Trojan and other wall-over software on Jetson, but they do not support on ARM architecture. Therefore, I would take the liberty to ask if I can add your contact information and send me your whl file.
> 
> Hi @Peppa-cs ,
> 
> Maybe you can try to find on [Gitee](https://gitee.com/). There are also many repositories which are clone from GitHub.
> I am sorry that I don't really understand what Chinese network problem is, so probably you can ask your classmates or other Chinese how to fix this problem because I believe you won't only need to build `onnxruntime` from source.
> 
> Thanks.

Thanks for your reply~

In fact, I have been plagued by this problem for almost three weeks. I have tried Gitee three weeks ago, but onnxruntime has a large number of submodules, and their submodules have a large number of submodules. Therefore, it is not enough to clone onnxruntime to Gitee, it is necessary to iteratively clone all submodules of Gitee. After I tried to clone all submodules to Gitee, the problem was not solved: I iteratively changed the .gitsubmodule module of all folders, but only the first level submodule can be modified. I have done a lot of experiments and found that it is necessary to change the version number pointed to by the upper layer from the bottom-level submodule. This work is very complicated. I have also asked my classmates from other schools, such as Shanghai Jiaotong University, but they are also unable to git clone resources from Google.

And thank you for your reply! I also think this behavior is shy. However, due to the reason of the mainland network, we cannot access Google if it does not pass a VPN. However, Jetson AGX is based on the ARM architecture. At present, I have not found a VPN suitable for the ARM architecture. I saw a discussion about this issue in the onnxruntime forum, so I contacted you. I am very sorry if it bothers you! Looking forward to your reply! :)

**Comment by Peppa-cs** [comment]
> > Hello, I am a graduate student on the mainland. I now use jetson for image classification. Since I can't access the external network on the mainland, after trying many methods, I still can't build onnxruntime. Because when building onnxruntime, you need to git clone the resources on Google. , I tried to use Trojan and other wall-over software on Jetson, but they do not support on ARM architecture. Therefore, I would take the liberty to ask if I can add your contact information and send me your whl file.
> 
> Hi @Peppa-cs ,
> 
> Maybe you can try to find on [Gitee](https://gitee.com/). There are also many repositories which are clone from GitHub.
> I am sorry that I don't really understand what Chinese network problem is, so probably you can ask your classmates or other Chinese how to fix this problem because I believe you won't only need to build `onnxruntime` from source.
> 
> Thanks.

Please do not worry that I will ask any questions other than this question! In fact, it took me a lot of courage to post this question. If it bothers you, I will delete this issue ~ thank you~:)

**Comment by chiehpower** [comment]
> Thanks for your reply~
> 
> In fact, I have been plagued by this problem for almost three weeks. I have tried Gitee three weeks ago, but onnxruntime has a large number of submodules, and their submodules have a large number of submodules. Therefore, it is not enough to clone onnxruntime to Gitee, it is necessary to iteratively clone all submodules of Gitee. After I tried to clone all submodules to Gitee, the problem was not solved: I iteratively changed the .gitsubmodule module of all folders, but only the first level submodule can be modified. I have done a lot of experiments and found that it is necessary to change the version number pointed to by the upper layer from the bottom-level submodule. This work is very complicated. I have also asked my classmates from other schools, such as Shanghai Jiaotong University, but they are also unable to git clone resources from Google.
> 
> And thank you for your reply! I also think this behavior is shy. However, due to the reason of the mainland network, we cannot access Google if it does not pass a VPN. However, Jetson AGX is based on the ARM architecture. At present, I have not found a VPN suitable for the ARM architecture. I saw a discussion about this issue in the onnxruntime forum, so I contacted you. I am very sorry if it bothers you! Looking forward to your reply! :)
>
> Please do not worry that I will ask any questions other than this question! In fact, it took me a lot of courage to post this question. If it bothers you, I will delete this issue ~ thank you~:)

Hi @Peppa-cs ,

I hear you. Thanks for your explanation.

There are a lot of submodules in onnxruntime and it is a big trouble as you saying. 
Unfortunately, if the thing is to send you the `.whl` file, I am sorry that I might decline you because the Jetson device is our company property and it is for business. Hence, I cannot share any document to outside.

Could you try to ask on [miivii](https://forum.miivii.com/forum.php?mod=forumdisplay&fid=2) or [NVIDIA forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-agx-xavier/75)? I don't think so no one didn't meet this issue before. There are many masters on NVIDIA forum. Hope you can find the solution on there. 

Thank you. :))
